"use client";

import { useRef, useState } from "react";
import { Download, FileArchive, ShieldCheck, Upload, WandSparkles } from "lucide-react";
import { chinesePdfCopy, chinesePdfHref, chinesePdfUi, type ChinesePdfLocale } from "./chinese-pdf-data";
import type { ProcessingOptions, ProcessResult } from "./pdf-actions";
import { toolSlugs, type ToolSlug } from "./tool-data";

const defaults: ProcessingOptions = { splitMode: "extract", pageRanges: "1", everyPages: 1, compression: "recommended", imagePageSize: "a4", imageOrientation: "auto", imageFormat: "jpg", imageScale: 1.5, rotation: 90, selectedPages: "", watermarkType: "text", watermarkText: "CONFIDENTIAL", watermarkImage: null, watermarkOpacity: 28, watermarkPosition: "center", watermarkSize: 42, password: "", allowPrint: true, allowCopy: false, allowModify: false, allowForms: true, organizeMode: "order", pageOrder: "1-3", deletePages: "1", pageNumberPosition: "bottom-center", pageNumberStart: 1 };

function Settings({ tool, locale, value, update }: { tool: ToolSlug; locale: ChinesePdfLocale; value: ProcessingOptions; update: <K extends keyof ProcessingOptions>(key: K, next: ProcessingOptions[K]) => void }) {
  const tw = locale === "zh-TW";
  const field = (label: string, key: keyof ProcessingOptions, type = "text") => <label className="field-label">{label}<input type={type} value={String(value[key] ?? "")} onChange={(event) => update(key, (type === "number" ? Number(event.target.value) : event.target.value) as never)} /></label>;
  if (tool === "merge-pdf") return <p className="setting-note">{tw ? "檔案會依選取順序合併；請先確認順序。" : "文件会按选择顺序合并；请先确认顺序。"}</p>;
  if (tool === "split-pdf") return <><label>{tw ? "分割方式" : "拆分方式"}</label><select value={value.splitMode} onChange={(e) => update("splitMode", e.target.value as ProcessingOptions["splitMode"])}><option value="extract">{tw ? "擷取指定頁面" : "提取指定页面"}</option><option value="ranges">{tw ? "依頁面群組分割" : "按页面分组拆分"}</option><option value="every">{tw ? "每 N 頁一份" : "每 N 页一份"}</option></select>{value.splitMode === "every" ? field(tw ? "每份頁數" : "每份页数", "everyPages", "number") : field(tw ? "頁面或範圍" : "页面或范围", "pageRanges")}</>;
  if (tool === "compress-pdf") return <label className="field-label">{tw ? "壓縮程度" : "压缩程度"}<select value={value.compression} onChange={(e) => update("compression", e.target.value as ProcessingOptions["compression"])}><option value="light">Light</option><option value="recommended">{tw ? "建議" : "推荐"}</option><option value="strong">Strong</option></select><small>{tw ? "Recommended 與 Strong 可能將頁面轉成圖片，表單、連結與可搜尋文字可能無法保留。" : "Recommended 和 Strong 可能将页面转换为图片，表单、链接和可搜索文字可能无法保留。"}</small></label>;
  if (tool === "images-to-pdf") return <><label className="field-label">{tw ? "紙張大小" : "页面大小"}<select value={value.imagePageSize} onChange={(e) => update("imagePageSize", e.target.value as ProcessingOptions["imagePageSize"])}><option value="auto">Auto</option><option value="a4">A4</option><option value="letter">Letter</option></select></label><label className="field-label">{tw ? "方向" : "方向"}<select value={value.imageOrientation} onChange={(e) => update("imageOrientation", e.target.value as ProcessingOptions["imageOrientation"])}><option value="auto">Auto</option><option value="portrait">{tw ? "直向" : "纵向"}</option><option value="landscape">{tw ? "橫向" : "横向"}</option></select></label></>;
  if (tool === "pdf-to-images") return <><label className="field-label">{tw ? "圖片格式" : "图片格式"}<select value={value.imageFormat} onChange={(e) => update("imageFormat", e.target.value as ProcessingOptions["imageFormat"])}><option value="jpg">JPG</option><option value="png">PNG</option></select></label><label className="field-label">{tw ? "解析度" : "分辨率"}<select value={value.imageScale} onChange={(e) => update("imageScale", Number(e.target.value))}><option value="1">Standard</option><option value="1.5">High</option><option value="2">Very high</option></select></label></>;
  if (tool === "rotate-pdf") return <><label className="field-label">{tw ? "順時針旋轉" : "顺时针旋转"}<select value={value.rotation} onChange={(e) => update("rotation", Number(e.target.value) as ProcessingOptions["rotation"])}><option value="90">90°</option><option value="180">180°</option><option value="270">270°</option></select></label>{field(tw ? "頁面（留白代表全部）" : "页面（留空代表全部）", "selectedPages")}</>;
  if (tool === "watermark-pdf") return <>{field(tw ? "浮水印文字" : "水印文字", "watermarkText")}<label className="field-label">{tw ? "透明度" : "透明度"}<input type="range" min="5" max="100" value={value.watermarkOpacity} onChange={(e) => update("watermarkOpacity", Number(e.target.value))} /></label>{field(tw ? "套用頁面（留白代表全部）" : "应用页面（留空代表全部）", "selectedPages")}</>;
  if (tool === "protect-pdf") return <>{field(tw ? "密碼（至少 8 個字元）" : "密码（至少 8 个字符）", "password", "password")}<p className="setting-note"><ShieldCheck size={15} /> AES-256 · {tw ? "請妥善保存密碼，DJAI 無法替你找回。" : "请妥善保存密码，DJAI 无法替你找回。"}</p></>;
  if (tool === "organize-pdf") return <>{field(tw ? "最後頁面順序" : "最终页面顺序", "pageOrder")}<p className="setting-note">{tw ? "未列出的頁面不會出現在新檔案中，原始 PDF 不會被修改。" : "未列出的页面不会出现在新文件中，原始 PDF 不会被修改。"}</p></>;
  if (tool === "add-page-numbers") return <><label className="field-label">{tw ? "頁碼位置" : "页码位置"}<select value={value.pageNumberPosition} onChange={(e) => update("pageNumberPosition", e.target.value as ProcessingOptions["pageNumberPosition"])}><option value="bottom-center">{tw ? "下方置中" : "底部居中"}</option><option value="bottom-right">{tw ? "右下" : "右下"}</option><option value="top-center">{tw ? "上方置中" : "顶部居中"}</option></select></label>{field(tw ? "起始頁碼" : "起始页码", "pageNumberStart", "number")}</>;
  return <p className="setting-note">{tw ? "將建立一份移除標題、作者、主旨、關鍵字與建立程式資訊的新副本，不會修改頁面內容。" : "将创建一份删除标题、作者、主题、关键词和创建程序信息的新副本，不会修改页面内容。"}</p>;
}

export default function ChinesePdfToolsApp({ locale, initialTool }: { locale: ChinesePdfLocale; initialTool?: ToolSlug }) {
  const copy = chinesePdfUi[locale]; const toolCopy = chinesePdfCopy[locale]; const active = initialTool || "merge-pdf"; const activeCopy = toolCopy[active];
  const [files, setFiles] = useState<File[]>([]); const [options, setOptions] = useState(defaults); const [processing, setProcessing] = useState(false); const [error, setError] = useState(""); const [result, setResult] = useState<(ProcessResult & { url: string }) | null>(null); const input = useRef<HTMLInputElement>(null);
  const images = active === "images-to-pdf"; const multiple = active === "merge-pdf" || images;
  function update<K extends keyof ProcessingOptions>(key: K, next: ProcessingOptions[K]) { setOptions((current) => ({ ...current, [key]: next })); }
  function clear() { if (result) URL.revokeObjectURL(result.url); setFiles([]); setResult(null); setError(""); setOptions(defaults); }
  async function run() { if (!files.length) return; if (active === "protect-pdf" && options.password.length < 8) { setError(locale === "zh-TW" ? "密碼至少需要 8 個字元。" : "密码至少需要 8 个字符。"); return; } setProcessing(true); setError(""); try { const { processFiles } = await import("./pdf-actions"); const output = await processFiles(active, files, options); if (result) URL.revokeObjectURL(result.url); setResult({ ...output, url: URL.createObjectURL(output.blob) }); } catch { setError(copy.error); } finally { setProcessing(false); } }
  return <main id="top" lang={locale}>
    <header className="site-header"><a className="brand" href={chinesePdfHref(undefined, locale)}><span><strong>DJTools</strong><small>PDF · by DJAI Academy</small></span></a><nav aria-label={copy.tools}><a href={`/tools/${locale === "zh-CN" ? "zh-cn" : "zh-tw"}/`}>{copy.tools}</a><a href={chinesePdfHref(initialTool, locale === "zh-CN" ? "zh-TW" : "zh-CN")} hrefLang={locale === "zh-CN" ? "zh-TW" : "zh-CN"}>{copy.switch}</a></nav></header>
    <section className="hero tool-hero"><div className="hero-content"><p className="eyebrow">DJTools by DJAI Academy</p><h1>{initialTool ? activeCopy.title : copy.title}</h1><p>{initialTool ? activeCopy.description : copy.intro}</p><a className="primary-button" href="#workspace">{copy.process}</a></div></section>
    {!initialTool && <section className="tools-section"><div className="section-heading"><h2>{copy.tools}</h2><p>{copy.intro}</p></div><div className="tools-grid">{toolSlugs.map((slug) => <a className="tool-card" href={chinesePdfHref(slug, locale)} key={slug}><span className="tool-icon"><FileArchive /></span><div><h3>{toolCopy[slug].label}</h3><p>{toolCopy[slug].description}</p></div></a>)}</div></section>}
    <section className="workspace-section" id="workspace"><div className="workspace-heading"><span className="tool-icon"><FileArchive /></span><div><p className="eyebrow">{copy.tools}</p><h2>{activeCopy.title}</h2></div></div><div className="workspace-card"><div className="upload-column"><button type="button" className="drop-zone" onClick={() => input.current?.click()}><span><Upload /></span><strong>{images ? copy.selectImages : copy.selectPdf}</strong><small>{images ? "JPG · PNG · WebP" : "PDF"}</small></button><input ref={input} className="visually-hidden" type="file" accept={images ? "image/jpeg,image/png,image/webp" : "application/pdf,.pdf"} multiple={multiple} aria-label={images ? copy.selectImages : copy.selectPdf} onChange={(event) => setFiles(Array.from(event.target.files || []))} />{files.length > 0 && <div className="file-list"><strong>{copy.selected}</strong>{files.map((file) => <div className="file-row" key={`${file.name}-${file.lastModified}`}><FileArchive /><span>{file.name}</span></div>)}</div>}</div><div className="settings-column"><div className="settings-title">{copy.settings}</div><Settings tool={active} locale={locale} value={options} update={update} />{error && <p className="error-message" role="alert">{error}</p>}<button className="process-button" type="button" disabled={!files.length || processing} onClick={run}><WandSparkles />{processing ? copy.processing : copy.process}</button><button className="clear-button" type="button" onClick={clear}>{copy.clear}</button></div></div></section>
    {result && <section className="result-section"><h2>{copy.ready}</h2><a className="download-button" href={result.url} download={result.fileName}><Download />{copy.download}</a></section>}
    {initialTool && <section className="tool-guide"><div><p className="eyebrow">{copy.how}</p><h2>{activeCopy.title}</h2></div><ol>{activeCopy.guide.map((step, index) => <li key={step}><span>0{index + 1}</span><p>{step}</p></li>)}</ol></section>}
    <section className="privacy-band"><ShieldCheck /><div><h2>{locale === "zh-CN" ? "在设计上保护隐私" : "從設計開始保護隱私"}</h2><p>{copy.privacy}</p></div></section>
    <footer><p>© 2026 DJTools by DJAI Academy</p></footer>
  </main>;
}
